import type { Lead } from "./schema.js";
import type { SelfState } from "../agent/state.js";
import { advance } from "../agent/state.js";
import { loadCaseType,loadJurisdiction,sourcesFor } from "../knowledge/registry.js";
import { missingRequirements,intakeHardStop,isMva } from "./requirements.js";
import { addEvidence,listEvidence } from "../evidence/ledger.js";
import { CLAIMS } from "../evidence/claims.js";
import { checkIncidentSource,checkRegistry } from "./source-check.js";
import { extractFaultFromDocuments,relevantDocumentText } from "./document.js";
import { buildOutcome } from "./outcome.js";
import { audit } from "../audit/log.js";
import { env } from "../config/env.js";
function ageDays(date?:string){if(!date)return null;const t=Date.parse(date);if(Number.isNaN(t))return null;return Math.floor((Date.now()-t)/86400000);}function pendingWindow(lead:Lead,pack:any){const age=ageDays(lead.incident.date);if(age===null||age<0)return false;if(lead.state==="FL")return age<=Number(pack.timing?.crash_report_max_submission_days??10);if(lead.state==="NY")return age<=Number(pack.timing?.paper_police_report_days??30);return age<=7;}function mvaFaultClaimSupportsProceeding(lead:Lead){return lead.qualification.primary_fault==="OTHER_PARTY"||lead.qualification.primary_fault==="NOT_SURE"||lead.qualification.primary_fault==="SHARED"||lead.qualification.client_claims_not_at_fault===true;}
export async function validateLead(validationId:string,lead:Lead,state:SelfState){
state.cycle++;advance(state,"NORMALIZED");const pack=loadJurisdiction(lead.state),skill=loadCaseType(lead.case_type);if(!pack||!skill)return buildOutcome({status:"INCOMPLETE",reason:"MISSING_INFORMATION",missing:["Unsupported jurisdiction or case type"],evidence:[],dimensions:{}});advance(state,"CLASSIFIED");state.knownFacts.push({key:"state",value:lead.state,state:"KNOWN"},{key:"case_type",value:lead.case_type,state:"KNOWN"});
const missing=missingRequirements(lead);advance(state,"REQUIREMENTS_CHECKED");if(missing.length){state.unknowns.push(...missing);return buildOutcome({status:"INCOMPLETE",reason:"MISSING_INFORMATION",missing,evidence:[],dimensions:{incident:"UNKNOWN",fault:"UNKNOWN"},nextAction:"REQUEST_MISSING_INTAKE_FIELDS"});}const hardStop=intakeHardStop(lead);if(hardStop)return buildOutcome({status:"CONTRADICTED",reason:hardStop,missing:[],evidence:[],dimensions:{intake_rule:hardStop},contradictions:[hardStop]});
for(const d of relevantDocumentText(lead))await addEvidence(validationId,{claim:CLAIMS.DOCUMENT_PRESENT,epistemicState:"KNOWN",sourceId:d.name,sourceType:"CLIENT_DOCUMENT",payload:{name:d.name,type:d.type,source:d.source,text_length:d.text.length}});
advance(state,"SOURCES_SELECTED");let incidentStatus:"VALIDATED"|"DOCUMENT_CORROBORATED"|"UNKNOWN"="UNKNOWN";const sourceErrors:string[]=[];if(isMva(lead)){advance(state,"INCIDENT_VALIDATION");for(const source of sourcesFor(lead.state,lead.case_type,"INCIDENT_EXISTENCE")){const checked=await checkIncidentSource(validationId,state,lead,source);if(checked.corroborated){incidentStatus="VALIDATED";break;}if(checked.reason)sourceErrors.push(`${source.id}: ${checked.reason}`);}const identifier=lead.incident.report_number??lead.incident.case_number;if(incidentStatus==="UNKNOWN"&&identifier){const doc=lead.documents.find((d:any)=>d.text&&["POLICE_REPORT","INCIDENT_REPORT"].includes(d.type)&&d.text.toLowerCase().includes(identifier.toLowerCase()));if(doc){incidentStatus="DOCUMENT_CORROBORATED";await addEvidence(validationId,{claim:CLAIMS.INCIDENT_IDENTIFIER_MATCH,epistemicState:"INFERRED",sourceId:doc.name,sourceType:"CLIENT_DOCUMENT",payload:{identifier_match:true,document:doc.name}});}}}else{advance(state,"INCIDENT_VALIDATION");const docs=lead.documents.filter((d:any)=>d.text&&d.type==="INCIDENT_REPORT");if(docs.length)incidentStatus="DOCUMENT_CORROBORATED";}
advance(state,"IDENTITY_CORRELATION");let identity:"MATCHED"|"UNKNOWN"="UNKNOWN";if(lead.client.first_name&&lead.client.last_name){const full=`${lead.client.first_name} ${lead.client.last_name}`.toLowerCase();const d=lead.documents.find((x:any)=>x.text?.toLowerCase().includes(full));if(d){identity="MATCHED";await addEvidence(validationId,{claim:CLAIMS.IDENTITY_MATCH,epistemicState:"INFERRED",sourceId:d.name,sourceType:"CLIENT_DOCUMENT",payload:{name_match:true}});}}
advance(state,"FAULT_EVIDENCE");let fault:"SUPPORTS_NOT_AT_FAULT"|"SUPPORTS_CLIENT_FAULT"|"COMPARATIVE_FAULT_INDICATORS"|"UNDETERMINED"="UNDETERMINED";if(isMva(lead)&&mvaFaultClaimSupportsProceeding(lead)){try{if(state.modelCalls<env.MAX_MODEL_CALLS){state.modelCalls++;const extraction=await extractFaultFromDocuments(lead);if(extraction){if(extraction.supports_client_fault)fault="SUPPORTS_CLIENT_FAULT";else if(extraction.comparative_fault_indicators)fault="COMPARATIVE_FAULT_INDICATORS";else if(extraction.supports_not_at_fault)fault="SUPPORTS_NOT_AT_FAULT";if(fault!=="UNDETERMINED")await addEvidence(validationId,{claim:fault==="SUPPORTS_NOT_AT_FAULT"?CLAIMS.SUPPORTS_NOT_AT_FAULT:fault==="SUPPORTS_CLIENT_FAULT"?CLAIMS.SUPPORTS_CLIENT_FAULT:CLAIMS.COMPARATIVE_FAULT,epistemicState:"INFERRED",sourceId:"CLIENT_DOCUMENT_ANALYSIS",sourceType:"CLIENT_DOCUMENT",payload:{rationale:extraction.rationale,confidence:extraction.confidence,matched_identifier:extraction.matched_identifier,matched_date:extraction.matched_date,matched_agency:extraction.matched_agency}});}}}catch(e:any){state.warnings.push(`FAULT_EXTRACTION:${e?.message??"FAILED"}`);}}
advance(state,"CASE_CHECKS");let business:"NOT_APPLICABLE"|"MATCHED"|"UNKNOWN"="NOT_APPLICABLE";if(lead.case_type==="SLIP_FALL"){business="UNKNOWN";const terms=[lead.incident.business_name??"",lead.incident.business_address??""];for(const source of sourcesFor(lead.state,lead.case_type,"BUSINESS_EXISTENCE")){const r=await checkRegistry(validationId,state,lead,source,terms,CLAIMS.BUSINESS_EXISTS,"BUSINESS_SEARCH");if(r.matched){business="MATCHED";break;}}}let provider:"NOT_REQUESTED"|"MATCHED"|"UNKNOWN"="NOT_REQUESTED";if(lead.medical.provider_name||lead.medical.provider_license){provider="UNKNOWN";const terms=[lead.medical.provider_name??"",lead.medical.provider_license??""];for(const source of sourcesFor(lead.state,lead.case_type,"PROVIDER_LICENSE")){const r=await checkRegistry(validationId,state,lead,source,terms,CLAIMS.PROVIDER_EXISTS,"PROVIDER_SEARCH");if(r.matched){provider="MATCHED";break;}}}
advance(state,"CONTRADICTION_CHECK");const contradictions:string[]=[];if(fault==="SUPPORTS_CLIENT_FAULT")contradictions.push("Observed document analysis supports client-primary-fault indicators, conflicting with intake non-fault requirement.");advance(state,"QUALIFICATION_ENGINE");const evidence=await listEvidence(validationId);await audit("VALIDATION_EVALUATED",validationId,{incidentStatus,identity,fault,business,provider,sourceErrors});
if(contradictions.length)return buildOutcome({status:"CONTRADICTED",reason:"FAULT_EVIDENCE_CONFLICT",missing:[],evidence,dimensions:{incident:incidentStatus,identity,fault,business,provider},contradictions,nextAction:"MANUAL_REVIEW"});if(isMva(lead)){if(incidentStatus==="UNKNOWN"){const authorizationRequired=sourceErrors.some(x=>x.includes("AUTHORIZATION_REQUIRED"));const reason=authorizationRequired?"AUTHORIZATION_REQUIRED":pendingWindow(lead,pack)?"RECORD_PENDING":"NOT_CORROBORATED";return buildOutcome({status:"INCOMPLETE",reason,missing:[authorizationRequired?"Authorization or a client-provided official report for restricted record access":"Authoritative incident existence or a matching official report document"],evidence,dimensions:{incident:incidentStatus,identity,fault,provider},nextAction:authorizationRequired?"REQUEST_CLIENT_REPORT_OR_AUTHORIZATION":pendingWindow(lead,pack)?"RETRY_AFTER_INDEXING_WINDOW":"REQUEST_POLICE_REPORT_OR_AUTHORIZED_RECORD"});}if(fault!=="SUPPORTS_NOT_AT_FAULT")return buildOutcome({status:"INCOMPLETE",reason:"FAULT_NOT_ESTABLISHED",missing:["Evidence supporting the intake requirement that the client was not primarily at fault"],evidence,dimensions:{incident:incidentStatus,identity,fault,provider},nextAction:"REQUEST_FAULT_SUPPORTING_POLICE_REPORT"});return buildOutcome({status:"VALIDATED",missing:[],evidence,dimensions:{incident:incidentStatus,identity,fault,provider}});}if(business!=="MATCHED")return buildOutcome({status:"INCOMPLETE",reason:"INSUFFICIENT_EVIDENCE",missing:["Premises/business existence match"],evidence,dimensions:{incident:incidentStatus,business,identity,provider},nextAction:"VERIFY_PREMISES_ENTITY"});if(incidentStatus==="UNKNOWN")return buildOutcome({status:"INCOMPLETE",reason:"INSUFFICIENT_EVIDENCE",missing:["Evidence that the premises incident occurred"],evidence,dimensions:{incident:incidentStatus,business,identity,provider},nextAction:"REQUEST_INCIDENT_REPORT_OR_OTHER_OCCURRENCE_EVIDENCE"});return buildOutcome({status:"VALIDATED",missing:[],evidence,dimensions:{incident:incidentStatus,business,identity,provider}});
}
