import { z } from "zod";
export const STATES=["FL","CA","AZ","TX","NY"] as const;
export const CASE_TYPES=["AUTO_ACCIDENT","TRUCK_ACCIDENT","MOTORCYCLE_ACCIDENT","RIDESHARE_ACCIDENT","BICYCLE_PEDESTRIAN","SLIP_FALL"] as const;
export const DOCUMENT_TYPES=["POLICE_REPORT","INCIDENT_REPORT","MEDICAL_RECORD","PHOTO","LAW_ENFORCEMENT_REPORT","STATE_CRASH_REPORT","POLICE_CRASH_REPORT","HIGHWAY_PATROL_REPORT","SHERIFF_REPORT","MUNICIPAL_POLICE_REPORT","DRIVER_SELF_REPORTED_CRASH_FORM","CRASH_EXCHANGE_INFORMATION_SHEET","SUPPLEMENTAL_REPORT","NARRATIVE","DIAGRAM","COMMERCIAL_VEHICLE_SUPPLEMENT","CONTINUATION_PAGE","DRIVER_LICENSE","STATE_ID","LEARNER_PERMIT","COMMERCIAL_DRIVER_LICENSE","TEMPORARY_DRIVER_LICENSE","MOBILE_ID_PRESENTATION","INSURANCE_CARD","INSURANCE_DECLARATION_PAGE","VEHICLE_REGISTRATION","VEHICLE_TITLE","ACCIDENT_PHOTOGRAPH","VEHICLE_DAMAGE_PHOTOGRAPH","SCENE_PHOTOGRAPH","SELFIE","IDENTITY_PHOTOGRAPH","SCREENSHOT","EMAIL_SCREENSHOT","TEXT_MESSAGE_SCREENSHOT","EMS_DOCUMENT","HOSPITAL_DOCUMENT","TOW_DOCUMENT","REPAIR_ESTIMATE","BODY_SHOP_ESTIMATE","RENTAL_DOCUMENT","UBER_DOCUMENT","LYFT_DOCUMENT","RIDESHARE_SCREENSHOT","PAYSTUB","PROOF_OF_ADDRESS","ATTORNEY_DOCUMENT","COURT_DOCUMENT","SIGNATURE","VIDEO","AUDIO","OTHER","UNKNOWN"] as const;
const Forensics=z.object({
  form_version_impossible:z.boolean().optional(),state_form_mismatch:z.boolean().optional(),authoritative_issuer_verified:z.boolean().optional(),authoritative_contradiction:z.boolean().optional(),machine_readable_consistent:z.boolean().optional(),
  sensitive_field_overlay:z.boolean().optional(),invalid_digital_signature:z.boolean().optional(),copy_move_detected:z.boolean().optional(),splice_detected:z.boolean().optional(),inpainting_detected:z.boolean().optional(),
  pdf417_decoded:z.boolean().optional(),barcode_visible_mismatch:z.boolean().optional(),issuer_jurisdiction_mismatch:z.boolean().optional(),credential_signature_valid:z.boolean().optional(),credential_signature_invalid:z.boolean().optional(),portrait_replacement_suspected:z.boolean().optional(),morph_result:z.enum(["MORPH_NOT_DETECTED","MORPH_SUSPECTED","MORPH_HIGH_RISK","MORPH_ANALYSIS_INCONCLUSIVE","NOT_PERFORMED"]).optional(),selfie_match:z.enum(["LIKELY_MATCH","POSSIBLE_MATCH","INCONCLUSIVE","LIKELY_MISMATCH","NOT_PERFORMED"]).optional(),
  c2pa_status:z.enum(["C2PA_VALID","C2PA_INVALID","C2PA_PRESENT_UNVERIFIED","C2PA_NOT_PRESENT"]).optional(),synthetic_media_result:z.enum(["NO_SYNTHETIC_INDICATORS","LOW_SYNTHETIC_RISK","SYNTHETIC_MEDIA_SUSPECTED","HIGH_SYNTHETIC_RISK","INCONCLUSIVE"]).optional(),duplicate_external_image:z.boolean().optional(),duplicate_unrelated_case:z.boolean().optional(),
  extracted_report_number:z.string().max(200).optional(),extracted_vin:z.string().max(40).optional(),extracted_plate:z.string().max(40).optional()
}).passthrough();
const Document=z.object({id:z.string().optional(),name:z.string().min(1),type:z.enum(DOCUMENT_TYPES).default("OTHER"),url:z.string().url().optional(),text:z.string().optional(),source:z.enum(["CLIENT","GOVERNMENT","PROVIDER","OTHER"]).default("CLIENT"),capture_type:z.enum(["ORIGINAL_DIGITAL_FILE","CAMERA_PHOTO_OF_DOCUMENT","SCREENSHOT","SCANNED_DOCUMENT","PHOTOCOPY","FAX","PRINT_AND_RESCAN","DIGITALLY_EDITED_DOCUMENT","COMPOSITE_IMAGE","GENERATED_IMAGE","UNKNOWN"]).optional(),forensics:Forensics.optional()});
export const Lead=z.object({
  lead_id:z.string().min(1).max(200),state:z.enum(STATES),case_type:z.enum(CASE_TYPES),
  client:z.object({first_name:z.string().max(100).optional(),last_name:z.string().max(100).optional(),email:z.string().email().optional(),date_of_birth:z.string().optional()}).default({}),
  incident:z.object({date:z.string().optional(),county:z.string().max(120).optional(),city:z.string().max(120).optional(),agency:z.string().max(200).optional(),report_number:z.string().max(120).optional(),case_number:z.string().max(120).optional(),location:z.string().max(500).optional(),business_name:z.string().max(300).optional(),business_address:z.string().max(500).optional(),carrier_name:z.string().max(300).optional(),usdot_number:z.string().max(30).optional()}).default({}),
  medical:z.object({provider_name:z.string().max(300).optional(),provider_license:z.string().max(120).optional(),npi:z.string().max(30).optional()}).default({}),
  qualification:z.object({injured:z.enum(["YES","NO","UNSURE"]).optional(),medical_treatment:z.boolean().optional(),primary_fault:z.enum(["OTHER_PARTY","NOT_SURE","SHARED","CLIENT"]).optional(),client_claims_not_at_fault:z.boolean().optional(),already_represented:z.boolean().optional()}).default({}),
  documents:z.array(Document).max(40).default([]),
  authorization:z.object({external_record_access:z.boolean().default(false),record_purchase:z.boolean().default(false)}).default({external_record_access:false,record_purchase:false}),
  metadata:z.record(z.unknown()).default({})
});
export type Lead=z.infer<typeof Lead>;export type CaseType=Lead["case_type"];export type StateCode=Lead["state"];export type FinalStatus="VALIDATED"|"INCOMPLETE"|"CONTRADICTED";
export type IncompleteReason="MISSING_INFORMATION"|"RECORD_PENDING"|"SOURCE_UNAVAILABLE"|"AUTHORIZATION_REQUIRED"|"IDENTITY_NOT_CONFIRMED"|"FAULT_NOT_ESTABLISHED"|"INSUFFICIENT_EVIDENCE"|"MANUAL_REVIEW_REQUIRED"|"NOT_CORROBORATED";
