export const CLAIMS = {
  INCIDENT_EXISTS: "INCIDENT_EXISTS",
  INCIDENT_IDENTIFIER_MATCH: "INCIDENT_IDENTIFIER_MATCH",
  IDENTITY_MATCH: "IDENTITY_MATCH",
  SUPPORTS_NOT_AT_FAULT: "SUPPORTS_NOT_AT_FAULT",
  SUPPORTS_CLIENT_FAULT: "SUPPORTS_CLIENT_FAULT",
  COMPARATIVE_FAULT: "COMPARATIVE_FAULT_INDICATORS",
  BUSINESS_EXISTS: "BUSINESS_EXISTS",
  PROVIDER_EXISTS: "PROVIDER_EXISTS",
  PROVIDER_LICENSE_ACTIVE: "PROVIDER_LICENSE_ACTIVE",
  LITIGATION_MATCH: "LITIGATION_MATCH",
  DOCUMENT_PRESENT: "DOCUMENT_PRESENT"
} as const;
